### ISSUE TITLE
makemigration vs makemigrations

### ISSUE THREAD

**Issue by aecio** [NYUAppSec/appsec_hw2#1]
Is there a typo in the following command?
```
python manage.py makemigration LegacySite
```

Here I get the following error:

```
$ python manage.py makemigration LegacySite
Unknown command: 'makemigration'. Did you mean makemigrations?
Type 'manage.py help' for usage.
```

Also, the Django version was not specified so I just installed it with `pip install django` and got version `3.1.2`.

Running `python manage.py makemigrations LegacySite`  seemed to work fine. But the following command, `python manage.py makemigrations`, didn't seem to make any changes. Is this expected?
```
$ python manage.py makemigrations LegacySite
Migrations for 'LegacySite':
  LegacySite/migrations/0001_initial.py
    - Create model Product
    - Create model User
    - Create model Card

$ python manage.py makemigrations
No changes detected
```

**Comment by moyix** [comment]
Yep, this was a typo. Fixed now, thanks!
